### ISSUE TITLE
incompatibility with stackable items mod (lets you have stacks up to 1 billion items

### ISSUE THREAD

**Issue by jakeyounglol** [Tiviacz1337/Travelers-Backpack#1288]
version: neoforge latest version on 1.21.5
mod: https://www.curseforge.com/minecraft/mc-mods/stackable-items

1. Describe the bug 
when i try to move items with a stack size over 99 it only puts 99 in the backpack

2. Write steps to reproduce the bug
1: install both mods (duh)
2: get a stack of items over 99
3: try to move it into a backpack
4: only 99 will go into the backpack, the rest will stay under your cursor

3. What is expected behavior 
it should put all of them into the backpack

4. Screenshots (If applicable)
this can only be depicted with a screen recording, which will be above the size limit of files i can upload here

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack
Fixed in latest version

**Comment by jakeyounglol** [comment]
it’s only partially fixed. it’s still broken in blast furnace and smoker

**Comment by Tiviacz1337** [comment]
Yes, I've expanded capacity only for backpack storage, I don't think it should be expandable in upgrades too

**Comment by jakeyounglol** [comment]
that’s kinda annoying because then i’ll have to constantly put coal in and store the rest in the actual backpack
