### ISSUE TITLE
Opening the backpack while wearing it causes the player to be disconnected from both SinglePlayer and Multiplayer worlds with OutofIndexRange error

### ISSUE THREAD

**Issue by NovaViper** [Tiviacz1337/Travelers-Backpack#982]
## ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
Minecraft v1.21
NeoForge v21.0.161
Travelers Backpack v10.0.3 from [Modrinth](https://modrinth.com/mod/travelersbackpack)

# Describe the bug 
When I equip the backpack and open it using the keybinding (C), it causes the game to kick me out of the world with `Failed to handle advanced open screen from server.`

# Write steps to reproduce the bug
1. Equip the backpack
2. Open it with backpack open keybinding
3. World crashes

# What is expected behaviour 
The backpack should just work normally

# Logs
https://mclo.gs/UQhrbqn

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/5601319
Fixed

**Comment by Deele** [comment]
Still crashes with recent update you mentioned.
```
[06Aug2024 14:32:08.785] [Render thread/ERROR] [net.neoforged.neoforge.network.handlers.ClientPayloadHandler/]: Failed to handle advanced open screen from server.
java.lang.IndexOutOfBoundsException: readerIndex(1) + length(1) exceeds writerIndex(1): UnpooledHeapByteBuf(ridx: 1, widx: 1, cap: 1/1)
	at MC-BOOTSTRAP/io.netty.buffer@4.1.97.Final/io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[netty-buffer-4.1.97.Final.jar%23147!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.buffer@4.1.97.Final/io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:730) ~[netty-buffer-4.1.97.Final.jar%23147!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.buffer@4.1.97.Final/io.netty.buffer.AbstractByteBuf.readBoolean(AbstractByteBuf.java:739) ~[netty-buffer-4.1.97.Final.jar%23147!/:4.1.97.Final]
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.FriendlyByteBuf.readBoolean(FriendlyByteBuf.java:1105) ~[client-1.21-20240613.152323-srg.jar%23253!/:?]
	at TRANSFORMER/travelersbackpack@10.0.3/com.tiviacz.travelersbackpack.inventory.menu.TravelersBackpackItemMenu.createInventory(TravelersBackpackItemMenu.java:46) ~[travelersbackpack-neoforge-1.21-10.0.3.jar%23321!/:?]
	at TRANSFORMER/travelersbackpack@10.0.3/com.tiviacz.travelersbackpack.inventory.menu.TravelersBackpackItemMenu.<init>(TravelersBackpackItemMenu.java:24) ~[travelersbackpack-neoforge-1.21-10.0.3.jar%23321!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.inventory.MenuType.create(MenuType.java:60) ~[client-1.21-20240613.152323-srg.jar%23253!/:?]
	at TRANSFORMER/neoforge@21.0.163/net.neoforged.neoforge.network.handlers.ClientPayloadHandler.lambda$createMenuScreen$0(ClientPayloadHandler.java:127) ~[neoforge-21.0.163-universal.jar%23254!/:?]
	at java.base/java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at TRANSFORMER/neoforge@21.0.163/net.neoforged.neoforge.network.handlers.ClientPayloadHandler.createMenuScreen(ClientPayloadHandler.java:126) ~[neoforge-21.0.163-universal.jar%23254!/:?]
	at TRANSFORMER/neoforge@21.0.163/net.neoforged.neoforge.network.handlers.ClientPayloadHandler.handle(ClientPayloadHandler.java:115) ~[neoforge-21.0.163-universal.jar%23254!/:?]
	at TRANSFORMER/neoforge@21.0.163/net.neoforged.neoforge.network.handling.MainThreadPayloadHandler.lambda$handle$0(MainThreadPayloadHandler.java:16) ~[neoforge-21.0.163-universal.jar%23254!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:60) ~[client-1.21-20240613.152323-srg.jar%23253!/:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:148) ~[client-1.21-20240613.152323-srg.jar%23253!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[client-1.21-20240613.152323-srg.jar%23253!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[client-1.21-20240613.152323-srg.jar%23253!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:111) ~[client-1.21-20240613.152323-srg.jar%23253!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.Minecraft.runTick(Minecraft.java:1155) ~[client-1.21-20240613.152323-srg.jar%23253!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.Minecraft.run(Minecraft.java:807) ~[client-1.21-20240613.152323-srg.jar%23253!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.main.Main.main(Main.java:230) ~[client-1.21-20240613.152323-srg.jar%23253!/:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136) ~[loader-4.0.23.jar%2398!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:124) ~[loader-4.0.23.jar%2398!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:32) ~[loader-4.0.23.jar%2398!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118) ~[loader-4.0.23.jar%2398!/:4.0]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-11.0.4.jar%23115!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-11.0.4.jar%23115!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-11.0.4.jar%23115!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:103) [modlauncher-11.0.4.jar%23115!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74) [modlauncher-11.0.4.jar%23115!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-11.0.4.jar%23115!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-11.0.4.jar%23115!/:?]
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210) [bootstraplauncher-2.0.2.jar:?]
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69) [bootstraplauncher-2.0.2.jar:?]
```

Update: Apologies, CurseForge client thinks Travelers Backpack v10.0.3 is a most recent update. When I go into versions dialog, and "Update" button prompts and switches to 10.0.3, while giving an option to "downgrade" to 10.0.4. Manually installing newest version fixed issue.
